
import React, { useState, useEffect, useRef, useMemo } from 'react';
import { createClient } from '@supabase/supabase-js';
import { motion, AnimatePresence } from 'framer-motion';
import { auditApiKeys } from '../lib/api';

interface SystemLogsProps {
  onBack: () => void;
}

export const SystemLogs: React.FC<SystemLogsProps> = ({ onBack }) => {
  const [logs, setLogs] = useState<string[]>([]);
  const [showSql, setShowSql] = useState(false);
  const terminalEndRef = useRef<HTMLDivElement>(null);

  const supabase = useMemo(() => {
    const vEnv = (import.meta as any).env || {};
    const url = vEnv.VITE_DATABASE_URL || 'https://urokqoorxuiokizesiwa.supabase.co';
    const key = vEnv.VITE_SUPABASE_ANON_KEY || 'sb_publishable_G1udRukMNJjDM6wlVD3xtw_IF8Yrbd8';
    return createClient(url, key);
  }, []);

  const addLog = (msg: string) => {
    setLogs(prev => [...prev, `[${new Date().toLocaleTimeString()}] ${msg}`]);
  };

  useEffect(() => {
    runAudit();
  }, []);

  useEffect(() => {
    terminalEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [logs]);

  const masterSql = `-- SATMOKO STUDIO ENGINE SETUP V7.7 FINAL
-- Jalankan ini di SQL Editor Supabase Anda untuk Replikasi

CREATE TABLE IF NOT EXISTS members (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  email text UNIQUE NOT NULL,
  full_name text,
  status text DEFAULT 'pending',
  credits bigint DEFAULT 0,
  valid_until timestamp with time zone,
  last_seen timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS topup_requests (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tid text UNIQUE NOT NULL,
  email text NOT NULL,
  amount bigint NOT NULL,
  price bigint NOT NULL,
  receipt_url text,
  status text DEFAULT 'pending',
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS direct_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_email text NOT NULL,
  receiver_email text NOT NULL,
  content text NOT NULL,
  is_read boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS settings (
  key text PRIMARY KEY,
  value jsonb NOT NULL
);

INSERT INTO settings (key, value) VALUES 
('cost_image', '25'),
('cost_video', '150'),
('cost_voice', '150'),
('cost_studio', '600')
ON CONFLICT (key) DO NOTHING;

ALTER TABLE members ENABLE ROW LEVEL SECURITY;
ALTER TABLE topup_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE direct_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public profiles viewable" ON members FOR SELECT USING (true);
CREATE POLICY "Update own presence" ON members FOR UPDATE USING (true);
CREATE POLICY "Public topup insert" ON topup_requests FOR INSERT WITH CHECK (true);
CREATE POLICY "Select own topup" ON topup_requests FOR SELECT USING (true);
CREATE POLICY "Chat access" ON direct_messages FOR ALL USING (true);
CREATE POLICY "Public settings" ON settings FOR SELECT USING (true);`;

  const masterPrompt = `PROMPT MASTER: SATMOKO AI ENGINE ARCHITECTURE v7.7 FINAL\n\n"Tugas Anda: Mereplikasi Sistem Satmoko Studio dengan arsitektur Full-Stack sebagai berikut:\n\n1. DATABASE (SUPABASE): Gunakan @supabase/supabase-js. Pastikan tabel 'members', 'topup_requests', 'direct_messages', dan 'settings' terkonfigurasi sesuai skema SQL Master.\n\n2. AUTH & SECURITY: Implementasikan LoginForm dengan mode Login/Register. User baru harus berstatus 'pending'. Whitelist email Admin di VITE_ADMIN_EMAILS untuk akses penuh (999.999 credits).\n\n3. AI CORE (GEMINI): Gunakan @google/genai SDK. Implementasikan sistem Multi-Key Rotation otomatis (Slot 1-3) untuk menghindari error 429. Gunakan model 'gemini-3-flash-preview' untuk Smart Logic dan 'gemini-3-pro-image-preview' untuk Visual Artist (4K).\n\n4. VIDEO ENGINE (VEO 3.1): Implementasikan VideoGenerator dengan kemampuan Image-to-Video dan Prompt-to-Video. Gunakan resolution '720p' dan pastikan pemotongan kredit (deductCredits) terpanggil sebelum API hit.\n\n5. UI/UX: Tema 'Cyberpunk Glassmorphism' dengan palet warna #020617 dan #22d3ee. Gunakan LandingHero sebagai animasi utama di halaman depan tepat di atas LoginForm. Slogan: 'ORA NGAPAK ORA KEPENAK'.\n\n6. TELEGRAM INTEGRATION: Kirim notifikasi bot untuk Login, Registrasi, Topup, dan Pesan Baru ke VITE_TELEGRAM_CHAT_ID."`;

  const runAudit = async () => {
    addLog("Memulai audit infrastruktur Satmoko V7.7 FINAL...");
    await new Promise(r => setTimeout(r, 400));
    addLog("Satmoko Engine v7.7_FINAL Terdeteksi");
    
    addLog("AUDIT SLOT PRODUKSI:");
    const keys = auditApiKeys();
    addLog(`Slot 1: ${keys.slot1 ? 'READY (Paten)' : 'OFF (Cek Hosting!)'}`);
    addLog(`Slot 2: ${keys.slot2 ? 'READY' : 'OFF'}`);
    addLog(`Slot 3: ${keys.slot3 ? 'READY' : 'OFF'}`);
    addLog(`Current Active Node: ${keys.activeSlot}`);

    addLog("Mengecek sinkronisasi Supabase...");
    try {
      const { error } = await supabase.from('members').select('id').limit(1);
      if (error) throw error;
      addLog("Database Status: SECURE & SYNCED");
    } catch {
      addLog("Database Status: OFFLINE / CONFIG ERR");
    }

    addLog("------------------------------------");
    addLog(">>> FINAL MASTER PROMPT EXTRACTED <<<");
    await new Promise(r => setTimeout(r, 600));
    addLog(masterPrompt);
    addLog("------------------------------------");
    addLog("Sistem Telah Dipatenkan. Master siap beroperasi.");
  };

  const copyPrompt = () => {
    navigator.clipboard.writeText(masterPrompt);
    alert("Master Prompt V7.7 FINAL Berhasil Disalin!");
  };

  const copySql = () => {
    navigator.clipboard.writeText(masterSql);
    alert("Final SQL Script Berhasil Disalin!");
  };

  return (
    <div className="space-y-6 flex flex-col h-[calc(100vh-140px)]">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div className="flex items-center gap-4">
          <button onClick={onBack} className="w-10 h-10 rounded-xl bg-white/5 border border-white/10 flex items-center justify-center text-slate-500 hover:text-white transition-all">
            <i className="fa-solid fa-chevron-left"></i>
          </button>
          <h2 className="text-2xl font-black italic uppercase tracking-tighter text-white">Console <span className="text-cyan-400">Master</span></h2>
        </div>
        <div className="flex gap-2">
          <button onClick={copyPrompt} className="px-4 py-2 bg-yellow-500 text-black text-[9px] font-black rounded-xl uppercase tracking-widest hover:bg-white transition-all shadow-lg">
             Salin Prompt Master
          </button>
          <button onClick={() => setShowSql(!showSql)} className={`px-4 py-2 rounded-xl text-[9px] font-black uppercase tracking-widest transition-all ${showSql ? 'bg-cyan-500 text-black' : 'bg-white/5 text-slate-500 border border-white/10'}`}>
             {showSql ? 'Tutup SQL' : 'Final SQL Script'}
          </button>
          <button onClick={() => { setLogs([]); runAudit(); }} className="w-10 h-10 bg-white/5 border border-white/10 text-slate-500 rounded-xl flex items-center justify-center hover:text-white">
             <i className="fa-solid fa-rotate"></i>
          </button>
        </div>
      </div>

      <div className="flex-1 glass-panel rounded-[2.5rem] bg-[#05070a] border-white/5 relative overflow-hidden shadow-2xl flex flex-col p-6 font-mono">
        <AnimatePresence mode="wait">
          {showSql ? (
            <motion.div key="sql" initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -10 }} className="h-full flex flex-col gap-4">
              <div className="flex justify-between items-center bg-white/5 p-3 rounded-xl">
                 <span className="text-[10px] text-cyan-400 font-black tracking-widest uppercase">Supabase V7.7 Final Schema</span>
                 <button onClick={copySql} className="px-3 py-1 bg-cyan-500 text-black text-[9px] font-black rounded-lg">COPY SQL</button>
              </div>
              <pre className="flex-1 bg-black/40 p-4 rounded-xl text-[10px] text-slate-400 overflow-auto whitespace-pre custom-scrollbar border border-white/5">
                {masterSql}
              </pre>
            </motion.div>
          ) : (
            <motion.div key="logs" initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="flex-1 overflow-y-auto custom-scrollbar pr-4 flex flex-col">
               <div className="space-y-2 py-4">
                  {logs.map((log, i) => (
                    <p key={i} className={`text-[10px] lg:text-[12px] leading-relaxed tracking-wider ${log.includes("READY (Paten)") ? "text-green-400 font-bold" : log.includes("PROMPT MASTER") ? "text-yellow-400 font-black bg-yellow-400/5 p-4 rounded-2xl border border-yellow-400/10 my-4" : "text-cyan-400/80 uppercase"}`}>
                      <span className="text-slate-700 mr-2">»</span>
                      {log}
                    </p>
                  ))}
                  <div className="flex items-center gap-2 mt-4">
                     <span className="text-slate-700 mr-2">»</span>
                     <motion.div animate={{ opacity: [0, 1, 0] }} transition={{ repeat: Infinity, duration: 0.8 }} className="w-2 h-4 bg-cyan-500/60" />
                  </div>
                  <div ref={terminalEndRef} />
               </div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </div>
  );
};
